env: "replenishment"

env_args:
  key: "replenishment_efficient_env-v0"
  # map_name: "different_order_cost"
  map_name: "sku10.single_store.standard"
  n_agents: 2
  # task_type: "different_order_cost"
  task_type: "sku10.single_store.standard"
  mode: train
  time_limit: 100
  reward: "reward2"
  