env: "replenishment"

env_args:
  key: "replenishment_efficient_env-v0"
  # map_name: "different_order_cost"
  map_name: "sku500.3_stores.standard"
  n_agents: 50
  # task_type: "different_order_cost"
  task_type: "sku500.3_stores.standard"
  mode: train
  time_limit: 100
  reward: "reward2"
  