# Normal sku 500 task with common setting.
# All skus are selected from sku2307 with minimum fluctuation demand.
env:
  mode:
    - name: train
      start_date: 2018/8/1
      end_date: 2021/6/30
      random_interception: True
    - name: validation
      start_date: 2021/7/1
      end_date: 2021/8/31 
    - name: test
      start_date: 2021/9/1
      end_date: 2021/10/30
  horizon: 100
  lookback_len: 7
  integerization_sku: True
  warmup: replenish_by_last_demand
  sku_list: 
    - SKU2

warehouse:
  - name: store2
    initial_balance: 0
    capacity: 200
    unit_storage_cost: 0.002
    accept_sku: equal_accept
    upstream: super_vendor
    downstream: store1
    sku:
      shared_data:
        init_stock: 0
        vlt: 2
        procurement_cost: 32
        selling_price: 36
        unit_order_cost: 200
        volume: 1
        basic_holding_cost: 0.001
        backlog_ratio: 0.1
        overflow_cost_ratio: 0.1
  - name: store1
    initial_balance: 0
    capacity: 50
    unit_storage_cost: 0.02
    accept_sku: equal_accept
    upstream: store2
    downstream: consumer
    sku:
      shared_data:
        init_stock: 50
        vlt: 2
        procurement_cost: 36
        selling_price: 40
        demand: 50
        unit_order_cost: 0
        volume: 1
        basic_holding_cost: 0.01
        backlog_ratio: 0.1
        overflow_cost_ratio: 1.0

profit_function: reward2

reward_function: reward2

action:
  mode: demand_mean_continuous

output_state:
  current_state:
    [selling_price, procurement_cost, vlt, volume, 
    unit_order_cost, replenish, excess, in_stock, in_transit]
  lookback_state:
    [demand]

visualization:
  state: 
    [demand, sale, arrived, replenish,
    excess, accepted, in_stock, in_transit]